# Generated by Django 2.2.7 on 2020-04-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20200403_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='person',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='quote.Person'),
            preserve_default=False,
        ),
    ]
