# Generated by Django 2.2.7 on 2020-04-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True)),
                ('event', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
            ],
        ),
    ]
