# Generated by Django 2.2.7 on 2020-04-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheer',
            name='events',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='project.Schedule'),
            preserve_default=False,
        ),
    ]
