# Generated by Django 2.2.7 on 2020-04-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmessage',
            name='image_file',
        ),
    ]
