# Generated by Django 2.2.7 on 2020-03-28 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facebook',
            new_name='Profile',
        ),
    ]
